import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

// Reliable curated food images from Unsplash
const IMAGES = {
  vegBiryani: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=700&auto=format&fit=crop&q=80',
  paneerBiryani: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?w=700&auto=format&fit=crop&q=80',
  chickenBiryani: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=700&auto=format&fit=crop&q=80',
  muttonBiryani: 'https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?w=700&auto=format&fit=crop&q=80',
  eggBiryani: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=700&auto=format&fit=crop&q=80',
  paneer65: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=700&auto=format&fit=crop&q=80',
  paneerTikka: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=700&auto=format&fit=crop&q=80',
  chicken65: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?w=700&auto=format&fit=crop&q=80',
  chickenLollipop: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=700&auto=format&fit=crop&q=80',
  chickenWings: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=700&auto=format&fit=crop&q=80',
  fishFry: 'https://images.unsplash.com/photo-1535400255456-984241443b29?w=700&auto=format&fit=crop&q=80',
  prawnsFry: 'https://images.unsplash.com/photo-1559742811-822873691df8?w=700&auto=format&fit=crop&q=80',
  crispyCorn: 'https://images.unsplash.com/photo-1551782450-a2132b4ba21d?w=700&auto=format&fit=crop&q=80',
  vegFriedRice: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=700&auto=format&fit=crop&q=80',
  chickenFriedRice: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=700&auto=format&fit=crop&q=80',
  paneerButterMasala: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=700&auto=format&fit=crop&q=80',
  butterChicken: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=700&auto=format&fit=crop&q=80',
  chickenCurry: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=700&auto=format&fit=crop&q=80',
  muttonCurry: 'https://images.unsplash.com/photo-1545247181-516773ca83f3?w=700&auto=format&fit=crop&q=80',
  naan: 'https://images.unsplash.com/photo-1626074353765-517a681e40be?w=700&auto=format&fit=crop&q=80',
  roti: 'https://images.unsplash.com/photo-1505253758473-96b3015f27eb?w=700&auto=format&fit=crop&q=80',
  vegNoodles: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=700&auto=format&fit=crop&q=80',
  chickenNoodles: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?w=700&auto=format&fit=crop&q=80',
  pizza: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=700&auto=format&fit=crop&q=80',
  burger: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=700&auto=format&fit=crop&q=80',
  fries: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?w=700&auto=format&fit=crop&q=80',
  sandwich: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=700&auto=format&fit=crop&q=80',
  iceCream: 'https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=700&auto=format&fit=crop&q=80',
  brownie: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=700&auto=format&fit=crop&q=80',
  gulabJamun: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=700&auto=format&fit=crop&q=80',
  rasmalai: 'https://images.unsplash.com/photo-1589119908995-c6837fa14d48?w=700&auto=format&fit=crop&q=80',
  beverage: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=700&auto=format&fit=crop&q=80',
  lassi: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=700&auto=format&fit=crop&q=80',
  coldCoffee: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=700&auto=format&fit=crop&q=80',
  milkshake: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=700&auto=format&fit=crop&q=80',
};

async function main() {
  console.log('Seeding DineDesk database...');

  // 1. Clear existing data
  await prisma.review.deleteMany();
  await prisma.orderItem.deleteMany();
  await prisma.order.deleteMany();
  await prisma.cartItem.deleteMany();
  await prisma.cart.deleteMany();
  await prisma.favorite.deleteMany();
  await prisma.address.deleteMany();
  await prisma.coupon.deleteMany();
  await prisma.food.deleteMany();
  await prisma.category.deleteMany();
  await prisma.user.deleteMany();

  console.log('Cleaned old records.');

  // 2. Seed Users
  const adminPassword = await bcrypt.hash('AdminPassword123!', 10);
  const customerPassword = await bcrypt.hash('CustomerPass123!', 10);

  const admin = await prisma.user.create({
    data: {
      name: 'Chef Rajesh (Admin)',
      email: 'admin@dinedesk.com',
      password: adminPassword,
      role: 'ADMIN',
      phone: '+91 98765 43210',
    },
  });

  const customer = await prisma.user.create({
    data: {
      name: 'Priya Sharma',
      email: 'customer@dinedesk.com',
      password: customerPassword,
      role: 'CUSTOMER',
      phone: '+91 91234 56789',
      cart: { create: {} },
    },
  });

  console.log('Users created: Admin & Customer');

  // 3. Seed Addresses
  const defaultAddress = await prisma.address.create({
    data: {
      userId: customer.id,
      label: 'Home',
      street: 'Flat 402, Royal Palms, Madhapur',
      city: 'Hyderabad',
      state: 'Telangana',
      postalCode: '500081',
      phone: '+91 91234 56789',
      isDefault: true,
    },
  });

  await prisma.address.create({
    data: {
      userId: customer.id,
      label: 'Office',
      street: 'Cyber Towers, 6th Floor, Hitech City',
      city: 'Hyderabad',
      state: 'Telangana',
      postalCode: '500081',
      phone: '+91 91234 56789',
      isDefault: false,
    },
  });

  // 4. Seed Categories
  const categoriesData = [
    { id: 'biryani', name: 'Biryani Specials', description: 'Royal dum cooked aromatic rice delicacies with rich spices', imageUrl: IMAGES.chickenBiryani },
    { id: 'starters', name: 'Appetizers & Starters', description: 'Crispy, spicy and flavorful starters to begin your culinary journey', imageUrl: IMAGES.paneer65 },
    { id: 'curries', name: 'Main Course Curries', description: 'Rich, aromatic curries cooked with authentic Indian herbs and spices', imageUrl: IMAGES.butterChicken },
    { id: 'rice', name: 'Rice & Fried Rice', description: 'Flavorful wok-tossed fried rice and traditional fragrant seasoned rice', imageUrl: IMAGES.vegFriedRice },
    { id: 'breads', name: 'Tandoori Breads', description: 'Freshly baked tandoori naans, rotis, and layered parathas', imageUrl: IMAGES.naan },
    { id: 'noodles', name: 'Wok Noodles', description: 'Smoky street-style noodles tossed with fresh veggies, sauces, and herbs', imageUrl: IMAGES.vegNoodles },
    { id: 'fast-food', name: 'Fast Food & Pizzas', description: 'Cheesy pizzas, handcrafted burgers, and crispy seasoned fries', imageUrl: IMAGES.burger },
    { id: 'desserts', name: 'Desserts & Sweets', description: 'Traditional Indian mithai, warm brownies, and creamy artisanal ice creams', imageUrl: IMAGES.gulabJamun },
    { id: 'beverages', name: 'Cold Beverages & Shakes', description: 'Refreshing mocktails, creamy milkshakes, classic sodas, and chilled lassis', imageUrl: IMAGES.lassi },
  ];

  for (const cat of categoriesData) {
    await prisma.category.create({ data: cat });
  }
  console.log('Categories created.');

  // 5. Food Menu Items (Comprehensive 75+ dishes)
  const foodsData = [
    // VEG BIRYANI
    {
      name: 'Veg Biryani',
      categoryId: 'biryani',
      foodType: 'VEG',
      price: 219,
      description: 'Layered aromatic basmati rice cooked with fresh seasonal vegetables, saffron, and traditional spices.',
      imageUrl: IMAGES.vegBiryani,
      rating: 4.6,
      reviewCount: 142,
      preparationTime: '25-30 min',
      featured: true,
    },
    {
      name: 'Paneer Biryani',
      categoryId: 'biryani',
      foodType: 'VEG',
      price: 249,
      description: 'Marinated cottage cheese cubes tossed in spicy biryani gravy and sealed in fragrant basmati layers.',
      imageUrl: IMAGES.paneerBiryani,
      rating: 4.8,
      reviewCount: 198,
      preparationTime: '25-30 min',
      featured: true,
    },
    {
      name: 'Mushroom Biryani',
      categoryId: 'biryani',
      foodType: 'VEG',
      price: 239,
      description: 'Tender button mushrooms simmered with aromatic herbs, whole spices, and rich saffron rice.',
      imageUrl: IMAGES.vegBiryani,
      rating: 4.5,
      reviewCount: 78,
      preparationTime: '25-30 min',
      featured: false,
    },

    // NON-VEG BIRYANI
    {
      name: 'Chicken Dum Biryani',
      categoryId: 'biryani',
      foodType: 'NON_VEG',
      price: 269,
      description: 'Signature Hyderabadi dum biryani with succulent chicken cuts slow-cooked to tender perfection in sealed handi.',
      imageUrl: IMAGES.chickenBiryani,
      rating: 4.9,
      reviewCount: 420,
      preparationTime: '30-35 min',
      featured: true,
    },
    {
      name: 'Chicken Fry Piece Biryani',
      categoryId: 'biryani',
      foodType: 'NON_VEG',
      price: 289,
      description: 'Rich spiced biryani rice topped with spicy Andhra style crispy fried chicken drumettes.',
      imageUrl: IMAGES.chickenBiryani,
      rating: 4.8,
      reviewCount: 230,
      preparationTime: '30-35 min',
      featured: true,
    },
    {
      name: 'Chicken 65 Biryani',
      categoryId: 'biryani',
      foodType: 'NON_VEG',
      price: 299,
      description: 'A fusion of fiery Chicken 65 bites tossed over fragrant basmati rice with mirchi ka salan.',
      imageUrl: IMAGES.chickenBiryani,
      rating: 4.7,
      reviewCount: 185,
      preparationTime: '30-35 min',
      featured: false,
    },
    {
      name: 'Mutton Biryani',
      categoryId: 'biryani',
      foodType: 'NON_VEG',
      price: 369,
      description: 'Tender prime mutton pieces slow-cooked with aged basmati rice, caramelized onions, and royal spices.',
      imageUrl: IMAGES.muttonBiryani,
      rating: 4.9,
      reviewCount: 310,
      preparationTime: '35-40 min',
      featured: true,
    },
    {
      name: 'Mutton Fry Piece Biryani',
      categoryId: 'biryani',
      foodType: 'NON_VEG',
      price: 389,
      description: 'Spicy pepper-fried boneless mutton bites served atop dum basmati biryani with raita.',
      imageUrl: IMAGES.muttonBiryani,
      rating: 4.8,
      reviewCount: 165,
      preparationTime: '35-40 min',
      featured: false,
    },
    {
      name: 'Egg Biryani',
      categoryId: 'biryani',
      foodType: 'NON_VEG',
      price: 209,
      description: 'Golden boiled eggs pan-seared with masala and layered between fragrant saffron rice.',
      imageUrl: IMAGES.eggBiryani,
      rating: 4.4,
      reviewCount: 92,
      preparationTime: '20-25 min',
      featured: false,
    },

    // VEG STARTERS
    {
      name: 'Paneer 65',
      categoryId: 'starters',
      foodType: 'VEG',
      price: 199,
      description: 'Crispy golden paneer cubes tossed with fresh curry leaves, green chillies, and spicy curd sauce.',
      imageUrl: IMAGES.paneer65,
      rating: 4.7,
      reviewCount: 175,
      preparationTime: '15-20 min',
      featured: true,
    },
    {
      name: 'Chilli Paneer',
      categoryId: 'starters',
      foodType: 'VEG',
      price: 209,
      description: 'Indo-Chinese style crispy paneer cubes wok-tossed with capsicum, onions, garlic, and dark soy sauce.',
      imageUrl: IMAGES.paneer65,
      rating: 4.6,
      reviewCount: 140,
      preparationTime: '15-20 min',
      featured: false,
    },
    {
      name: 'Gobi 65',
      categoryId: 'starters',
      foodType: 'VEG',
      price: 179,
      description: 'Crispy batter-fried cauliflower florets seasoned with aromatic south Indian spices and curry leaves.',
      imageUrl: IMAGES.crispyCorn,
      rating: 4.5,
      reviewCount: 110,
      preparationTime: '15-20 min',
      featured: false,
    },
    {
      name: 'Gobi Manchurian',
      categoryId: 'starters',
      foodType: 'VEG',
      price: 189,
      description: 'Deep-fried cauliflower balls tossed in a tangy, spicy ginger-garlic Manchurian glaze.',
      imageUrl: IMAGES.crispyCorn,
      rating: 4.6,
      reviewCount: 128,
      preparationTime: '15-20 min',
      featured: false,
    },
    {
      name: 'Crispy Corn',
      categoryId: 'starters',
      foodType: 'VEG',
      price: 169,
      description: 'Crunchy golden sweet corn kernels dusted with chatpata masala, lemon zest, and spring onions.',
      imageUrl: IMAGES.crispyCorn,
      rating: 4.6,
      reviewCount: 190,
      preparationTime: '10-15 min',
      featured: true,
    },
    {
      name: 'Baby Corn Manchurian',
      categoryId: 'starters',
      foodType: 'VEG',
      price: 189,
      description: 'Tender baby corn spears fried crisp and sauteed in savory oriental garlic chilli sauce.',
      imageUrl: IMAGES.crispyCorn,
      rating: 4.4,
      reviewCount: 84,
      preparationTime: '15-20 min',
      featured: false,
    },
    {
      name: 'Mushroom 65',
      categoryId: 'starters',
      foodType: 'VEG',
      price: 199,
      description: 'Juicy whole button mushrooms battered in spiced flour and fried crisp with tempering.',
      imageUrl: IMAGES.paneer65,
      rating: 4.5,
      reviewCount: 72,
      preparationTime: '15-20 min',
      featured: false,
    },
    {
      name: 'Paneer Tikka',
      categoryId: 'starters',
      foodType: 'VEG',
      price: 229,
      description: 'Char-grilled cottage cheese skewers marinated in spiced hung yogurt with bell peppers and onions.',
      imageUrl: IMAGES.paneerTikka,
      rating: 4.8,
      reviewCount: 220,
      preparationTime: '20-25 min',
      featured: true,
    },

    // NON-VEG STARTERS
    {
      name: 'Chicken 65',
      categoryId: 'starters',
      foodType: 'NON_VEG',
      price: 239,
      description: 'Legendary spicy boneless chicken bites tempered with green chillies, garlic, and crunchy curry leaves.',
      imageUrl: IMAGES.chicken65,
      rating: 4.9,
      reviewCount: 350,
      preparationTime: '20-25 min',
      featured: true,
    },
    {
      name: 'Chicken 555',
      categoryId: 'starters',
      foodType: 'NON_VEG',
      price: 249,
      description: 'Crispy shredded chicken strips wok-tossed in a creamy, mildly spiced garlic-cashew sauce.',
      imageUrl: IMAGES.chicken65,
      rating: 4.7,
      reviewCount: 160,
      preparationTime: '20-25 min',
      featured: false,
    },
    {
      name: 'Chilli Chicken',
      categoryId: 'starters',
      foodType: 'NON_VEG',
      price: 239,
      description: 'Tender chicken tossed with diced bell peppers, red onions, garlic, and hot Asian chilli sauce.',
      imageUrl: IMAGES.chicken65,
      rating: 4.7,
      reviewCount: 215,
      preparationTime: '15-20 min',
      featured: false,
    },
    {
      name: 'Chicken Manchurian',
      categoryId: 'starters',
      foodType: 'NON_VEG',
      price: 239,
      description: 'Golden fried chicken morsels cooked in a savory, aromatic scallion and soy Manchurian reduction.',
      imageUrl: IMAGES.chicken65,
      rating: 4.6,
      reviewCount: 145,
      preparationTime: '15-20 min',
      featured: false,
    },
    {
      name: 'Chicken Lollipop',
      categoryId: 'starters',
      foodType: 'NON_VEG',
      price: 259,
      description: 'Frenched chicken winglets deep fried to a crispy red crunch, served with hot schezwan dip.',
      imageUrl: IMAGES.chickenLollipop,
      rating: 4.8,
      reviewCount: 280,
      preparationTime: '20-25 min',
      featured: true,
    },
    {
      name: 'Chicken Wings',
      categoryId: 'starters',
      foodType: 'NON_VEG',
      price: 249,
      description: 'Juicy wings tossed in our signature smoky barbecue spice rub with a spicy glaze.',
      imageUrl: IMAGES.chickenWings,
      rating: 4.6,
      reviewCount: 130,
      preparationTime: '20-25 min',
      featured: false,
    },
    {
      name: 'Crispy Chicken',
      categoryId: 'starters',
      foodType: 'NON_VEG',
      price: 249,
      description: 'Golden-crumbed chicken tenders marinated with herbs, fried crunchy, and served with garlic mayo.',
      imageUrl: IMAGES.chicken65,
      rating: 4.5,
      reviewCount: 112,
      preparationTime: '15-20 min',
      featured: false,
    },
    {
      name: 'Pepper Chicken',
      categoryId: 'starters',
      foodType: 'NON_VEG',
      price: 249,
      description: 'South Indian dry fry with tender chicken pieces coated in freshly crushed black pepper and onions.',
      imageUrl: IMAGES.chicken65,
      rating: 4.7,
      reviewCount: 174,
      preparationTime: '20-25 min',
      featured: false,
    },
    {
      name: 'Mutton Fry',
      categoryId: 'starters',
      foodType: 'NON_VEG',
      price: 349,
      description: 'Slow-roasted succulent mutton cubes braised in thick pepper-shallot masala until golden dry.',
      imageUrl: IMAGES.muttonCurry,
      rating: 4.8,
      reviewCount: 195,
      preparationTime: '25-30 min',
      featured: true,
    },
    {
      name: 'Fish Fry',
      categoryId: 'starters',
      foodType: 'NON_VEG',
      price: 289,
      description: 'Fresh boneless fish fillets rubbed with coastal masala and tawa-fried to a delicate golden crisp.',
      imageUrl: IMAGES.fishFry,
      rating: 4.7,
      reviewCount: 140,
      preparationTime: '15-20 min',
      featured: true,
    },
    {
      name: 'Chilli Fish',
      categoryId: 'starters',
      foodType: 'NON_VEG',
      price: 299,
      description: 'Delicate crispy fish nuggets tossed in oriental chilli soya sauce with crunchy peppers.',
      imageUrl: IMAGES.fishFry,
      rating: 4.6,
      reviewCount: 88,
      preparationTime: '15-20 min',
      featured: false,
    },
    {
      name: 'Prawns Fry',
      categoryId: 'starters',
      foodType: 'NON_VEG',
      price: 329,
      description: 'Plump tiger prawns sauteed with aromatic curry leaves, black pepper, and crushed garlic.',
      imageUrl: IMAGES.prawnsFry,
      rating: 4.8,
      reviewCount: 162,
      preparationTime: '15-20 min',
      featured: true,
    },

    // VEG RICE
    {
      name: 'Veg Fried Rice',
      categoryId: 'rice',
      foodType: 'VEG',
      price: 179,
      description: 'Steamed fragrant rice wok-tossed with finely diced carrots, beans, cabbage, and light seasoning.',
      imageUrl: IMAGES.vegFriedRice,
      rating: 4.5,
      reviewCount: 154,
      preparationTime: '15-20 min',
      featured: false,
    },
    {
      name: 'Schezwan Veg Fried Rice',
      categoryId: 'rice',
      foodType: 'VEG',
      price: 189,
      description: 'Spicy wok-fried rice blended with homemade Schezwan chilli pepper paste and crisp scallions.',
      imageUrl: IMAGES.vegFriedRice,
      rating: 4.6,
      reviewCount: 130,
      preparationTime: '15-20 min',
      featured: false,
    },
    {
      name: 'Paneer Fried Rice',
      categoryId: 'rice',
      foodType: 'VEG',
      price: 209,
      description: 'A hearty blend of stir-fried basmati rice with pan-seared paneer cubes and crunchy veggies.',
      imageUrl: IMAGES.vegFriedRice,
      rating: 4.7,
      reviewCount: 145,
      preparationTime: '15-20 min',
      featured: false,
    },
    {
      name: 'Ghee Rice',
      categoryId: 'rice',
      foodType: 'VEG',
      price: 169,
      description: 'Rich basmati rice cooked in pure desi ghee with whole spices, fried cashews, and golden raisins.',
      imageUrl: IMAGES.vegFriedRice,
      rating: 4.6,
      reviewCount: 95,
      preparationTime: '15-20 min',
      featured: false,
    },
    {
      name: 'Jeera Rice',
      categoryId: 'rice',
      foodType: 'VEG',
      price: 149,
      description: 'Light basmati rice tempered with roasted cumin seeds and fresh coriander leaves.',
      imageUrl: IMAGES.vegFriedRice,
      rating: 4.4,
      reviewCount: 88,
      preparationTime: '15-20 min',
      featured: false,
    },

    // NON-VEG RICE
    {
      name: 'Chicken Fried Rice',
      categoryId: 'rice',
      foodType: 'NON_VEG',
      price: 219,
      description: 'Classic wok-tossed rice with tender shredded chicken, egg ribbons, and fresh garden veggies.',
      imageUrl: IMAGES.chickenFriedRice,
      rating: 4.7,
      reviewCount: 260,
      preparationTime: '15-20 min',
      featured: true,
    },
    {
      name: 'Schezwan Chicken Fried Rice',
      categoryId: 'rice',
      foodType: 'NON_VEG',
      price: 229,
      description: 'Wok-charred chicken and rice infused with fiery red Schezwan sauce and garlic.',
      imageUrl: IMAGES.chickenFriedRice,
      rating: 4.8,
      reviewCount: 205,
      preparationTime: '15-20 min',
      featured: false,
    },
    {
      name: 'Egg Fried Rice',
      categoryId: 'rice',
      foodType: 'NON_VEG',
      price: 189,
      description: 'Fluffy scrambled eggs stir-fried with basmati rice, spring onions, and white pepper.',
      imageUrl: IMAGES.chickenFriedRice,
      rating: 4.5,
      reviewCount: 140,
      preparationTime: '15-20 min',
      featured: false,
    },
    {
      name: 'Chicken 65 Fried Rice',
      categoryId: 'rice',
      foodType: 'NON_VEG',
      price: 249,
      description: 'Special wok rice loaded with diced spicy Chicken 65 nuggets and curry leaf tempering.',
      imageUrl: IMAGES.chickenFriedRice,
      rating: 4.8,
      reviewCount: 180,
      preparationTime: '15-20 min',
      featured: true,
    },
    {
      name: 'Mutton Fried Rice',
      categoryId: 'rice',
      foodType: 'NON_VEG',
      price: 299,
      description: 'Savory fried rice prepared with tender minced mutton bits and aromatic whole spices.',
      imageUrl: IMAGES.chickenFriedRice,
      rating: 4.7,
      reviewCount: 95,
      preparationTime: '20-25 min',
      featured: false,
    },

    // VEG CURRIES
    {
      name: 'Paneer Butter Masala',
      categoryId: 'curries',
      foodType: 'VEG',
      price: 239,
      description: 'Silky cottage cheese cubes simmered in a velvety, mildly spiced butter and tomato gravy.',
      imageUrl: IMAGES.paneerButterMasala,
      rating: 4.9,
      reviewCount: 380,
      preparationTime: '20-25 min',
      featured: true,
    },
    {
      name: 'Kadai Paneer',
      categoryId: 'curries',
      foodType: 'VEG',
      price: 249,
      description: 'Paneer tossed with crunchy bell peppers and freshly ground kadai coriander-chilli masala.',
      imageUrl: IMAGES.paneerButterMasala,
      rating: 4.7,
      reviewCount: 190,
      preparationTime: '20-25 min',
      featured: false,
    },
    {
      name: 'Palak Paneer',
      categoryId: 'curries',
      foodType: 'VEG',
      price: 229,
      description: 'Soft cottage cheese immersed in pureed fresh spinach gravy infused with garlic and cumin.',
      imageUrl: IMAGES.paneerButterMasala,
      rating: 4.6,
      reviewCount: 160,
      preparationTime: '20-25 min',
      featured: false,
    },
    {
      name: 'Mixed Veg Curry',
      categoryId: 'curries',
      foodType: 'VEG',
      price: 199,
      description: 'A wholesome melange of cauliflower, beans, potatoes, and peas in onion-tomato curry.',
      imageUrl: IMAGES.paneerButterMasala,
      rating: 4.4,
      reviewCount: 90,
      preparationTime: '20-25 min',
      featured: false,
    },
    {
      name: 'Mushroom Curry',
      categoryId: 'curries',
      foodType: 'VEG',
      price: 219,
      description: 'Sliced button mushrooms cooked in an aromatic, homestyle spiced onion and cashew gravy.',
      imageUrl: IMAGES.paneerButterMasala,
      rating: 4.5,
      reviewCount: 82,
      preparationTime: '20-25 min',
      featured: false,
    },
    {
      name: 'Veg Kolhapuri',
      categoryId: 'curries',
      foodType: 'VEG',
      price: 229,
      description: 'A fiery Maharashtrian curry made with assorted veggies and roasted Kolhapuri spice blend.',
      imageUrl: IMAGES.paneerButterMasala,
      rating: 4.5,
      reviewCount: 96,
      preparationTime: '20-25 min',
      featured: false,
    },

    // NON-VEG CURRIES
    {
      name: 'Butter Chicken',
      categoryId: 'curries',
      foodType: 'NON_VEG',
      price: 279,
      description: 'Tender tandoori chicken shredded and bathed in rich makhani gravy with butter and fenugreek leaves.',
      imageUrl: IMAGES.butterChicken,
      rating: 4.9,
      reviewCount: 450,
      preparationTime: '20-25 min',
      featured: true,
    },
    {
      name: 'Chicken Curry',
      categoryId: 'curries',
      foodType: 'NON_VEG',
      price: 249,
      description: 'Traditional homestyle chicken curry cooked with onions, tomatoes, ginger, and ground garam masala.',
      imageUrl: IMAGES.chickenCurry,
      rating: 4.7,
      reviewCount: 220,
      preparationTime: '20-25 min',
      featured: false,
    },
    {
      name: 'Kadai Chicken',
      categoryId: 'curries',
      foodType: 'NON_VEG',
      price: 269,
      description: 'Chicken pieces braised with thick capsicum gravy, whole red chillies, and roasted coriander.',
      imageUrl: IMAGES.chickenCurry,
      rating: 4.7,
      reviewCount: 175,
      preparationTime: '20-25 min',
      featured: false,
    },
    {
      name: 'Chicken Tikka Masala',
      categoryId: 'curries',
      foodType: 'NON_VEG',
      price: 289,
      description: 'Smoky grilled chicken tikka folded into a luscious, spiced tomato cream sauce.',
      imageUrl: IMAGES.butterChicken,
      rating: 4.8,
      reviewCount: 290,
      preparationTime: '20-25 min',
      featured: true,
    },
    {
      name: 'Pepper Chicken Curry',
      categoryId: 'curries',
      foodType: 'NON_VEG',
      price: 269,
      description: 'Andhra style dark chicken curry enriched with crushed black peppercorns and curry leaves.',
      imageUrl: IMAGES.chickenCurry,
      rating: 4.6,
      reviewCount: 135,
      preparationTime: '20-25 min',
      featured: false,
    },
    {
      name: 'Mutton Curry',
      categoryId: 'curries',
      foodType: 'NON_VEG',
      price: 369,
      description: 'Tender bone-in mutton slow-simmered in hearty onion gravy with cardamom, cloves, and cinnamon.',
      imageUrl: IMAGES.muttonCurry,
      rating: 4.8,
      reviewCount: 240,
      preparationTime: '30-35 min',
      featured: true,
    },
    {
      name: 'Mutton Rogan Josh',
      categoryId: 'curries',
      foodType: 'NON_VEG',
      price: 389,
      description: 'Kashmiri delicacy of lamb cooked with Kashmiri red chillies, fennel, and browned onions.',
      imageUrl: IMAGES.muttonCurry,
      rating: 4.9,
      reviewCount: 195,
      preparationTime: '30-35 min',
      featured: true,
    },
    {
      name: 'Fish Curry',
      categoryId: 'curries',
      foodType: 'NON_VEG',
      price: 299,
      description: 'Fresh fish fillets cooked in tangy tamarind and coconut milk coastal gravy.',
      imageUrl: IMAGES.fishFry,
      rating: 4.6,
      reviewCount: 110,
      preparationTime: '20-25 min',
      featured: false,
    },
    {
      name: 'Prawn Curry',
      categoryId: 'curries',
      foodType: 'NON_VEG',
      price: 339,
      description: 'Succulent prawns gently simmered in mild coconut cream gravy flavored with kokum and curry leaves.',
      imageUrl: IMAGES.prawnsFry,
      rating: 4.8,
      reviewCount: 145,
      preparationTime: '20-25 min',
      featured: false,
    },

    // VEG ROTIS / BREADS
    {
      name: 'Butter Naan',
      categoryId: 'breads',
      foodType: 'VEG',
      price: 45,
      description: 'Clay-oven baked leavened flatbread brushed with generous salted butter.',
      imageUrl: IMAGES.naan,
      rating: 4.8,
      reviewCount: 410,
      preparationTime: '5-10 min',
      featured: true,
    },
    {
      name: 'Plain Naan',
      categoryId: 'breads',
      foodType: 'VEG',
      price: 40,
      description: 'Classic leavened soft white bread baked in clay tandoor.',
      imageUrl: IMAGES.naan,
      rating: 4.5,
      reviewCount: 120,
      preparationTime: '5-10 min',
      featured: false,
    },
    {
      name: 'Garlic Naan',
      categoryId: 'breads',
      foodType: 'VEG',
      price: 55,
      description: 'Tandoori naan topped with roasted minced garlic, fresh coriander, and melted butter.',
      imageUrl: IMAGES.naan,
      rating: 4.9,
      reviewCount: 380,
      preparationTime: '5-10 min',
      featured: true,
    },
    {
      name: 'Tandoori Roti',
      categoryId: 'breads',
      foodType: 'VEG',
      price: 30,
      description: 'Healthy whole wheat flatbread crisp-baked in traditional charcoal tandoor.',
      imageUrl: IMAGES.roti,
      rating: 4.6,
      reviewCount: 220,
      preparationTime: '5-10 min',
      featured: false,
    },
    {
      name: 'Butter Roti',
      categoryId: 'breads',
      foodType: 'VEG',
      price: 35,
      description: 'Whole wheat tandoori roti glazed with golden butter.',
      imageUrl: IMAGES.roti,
      rating: 4.6,
      reviewCount: 180,
      preparationTime: '5-10 min',
      featured: false,
    },
    {
      name: 'Laccha Paratha',
      categoryId: 'breads',
      foodType: 'VEG',
      price: 50,
      description: 'Multi-layered flaky whole wheat flatbread roasted to crisp golden finish.',
      imageUrl: IMAGES.roti,
      rating: 4.7,
      reviewCount: 160,
      preparationTime: '10-15 min',
      featured: false,
    },
    {
      name: 'Paneer Kulcha',
      categoryId: 'breads',
      foodType: 'VEG',
      price: 65,
      description: 'Crispy Amritsari leavened bread stuffed with spiced crumbled paneer and herbs.',
      imageUrl: IMAGES.naan,
      rating: 4.8,
      reviewCount: 195,
      preparationTime: '10-15 min',
      featured: true,
    },

    // VEG NOODLES
    {
      name: 'Veg Hakka Noodles',
      categoryId: 'noodles',
      foodType: 'VEG',
      price: 179,
      description: 'Wok-tossed noodles with shredded cabbage, carrots, bell peppers, and scallions in light soy.',
      imageUrl: IMAGES.vegNoodles,
      rating: 4.6,
      reviewCount: 195,
      preparationTime: '15-20 min',
      featured: true,
    },
    {
      name: 'Schezwan Veg Noodles',
      categoryId: 'noodles',
      foodType: 'VEG',
      price: 189,
      description: 'Fiery wok noodles tossed with tangy Schezwan pepper sauce and crisp garden vegetables.',
      imageUrl: IMAGES.vegNoodles,
      rating: 4.6,
      reviewCount: 140,
      preparationTime: '15-20 min',
      featured: false,
    },
    {
      name: 'Paneer Noodles',
      categoryId: 'noodles',
      foodType: 'VEG',
      price: 209,
      description: 'Stir-fried noodles loaded with golden paneer strips, broccoli, and fragrant Chinese spices.',
      imageUrl: IMAGES.vegNoodles,
      rating: 4.7,
      reviewCount: 120,
      preparationTime: '15-20 min',
      featured: false,
    },

    // NON-VEG NOODLES
    {
      name: 'Chicken Noodles',
      categoryId: 'noodles',
      foodType: 'NON_VEG',
      price: 219,
      description: 'Savory noodles tossed with tender chicken chunks, scrambled egg, and fresh crunchy vegetables.',
      imageUrl: IMAGES.chickenNoodles,
      rating: 4.7,
      reviewCount: 240,
      preparationTime: '15-20 min',
      featured: true,
    },
    {
      name: 'Schezwan Chicken Noodles',
      categoryId: 'noodles',
      foodType: 'NON_VEG',
      price: 229,
      description: 'Spicy wok-tossed noodles with chicken strips and homemade fiery red Schezwan pepper sauce.',
      imageUrl: IMAGES.chickenNoodles,
      rating: 4.8,
      reviewCount: 190,
      preparationTime: '15-20 min',
      featured: false,
    },
    {
      name: 'Egg Noodles',
      categoryId: 'noodles',
      foodType: 'NON_VEG',
      price: 189,
      description: 'Wok-fried egg noodles with scrambled egg ribbons, onion greens, and toasted sesame.',
      imageUrl: IMAGES.chickenNoodles,
      rating: 4.5,
      reviewCount: 115,
      preparationTime: '15-20 min',
      featured: false,
    },
    {
      name: 'Chicken Hakka Noodles',
      categoryId: 'noodles',
      foodType: 'NON_VEG',
      price: 229,
      description: 'Traditional Indo-Chinese street-style hakka noodles with roasted chicken bits and soy.',
      imageUrl: IMAGES.chickenNoodles,
      rating: 4.7,
      reviewCount: 165,
      preparationTime: '15-20 min',
      featured: false,
    },

    // FAST FOOD
    {
      name: 'Chicken Pizza',
      categoryId: 'fast-food',
      foodType: 'NON_VEG',
      price: 289,
      description: 'Hand-stretched crust topped with barbecue chicken cubes, mozzarella cheese, and capsicum.',
      imageUrl: IMAGES.pizza,
      rating: 4.8,
      reviewCount: 230,
      preparationTime: '20-25 min',
      featured: true,
    },
    {
      name: 'Paneer Pizza',
      categoryId: 'fast-food',
      foodType: 'VEG',
      price: 259,
      description: 'Stone-baked pizza loaded with spicy marinated paneer, black olives, jalapenos, and mozzarella.',
      imageUrl: IMAGES.pizza,
      rating: 4.7,
      reviewCount: 180,
      preparationTime: '20-25 min',
      featured: true,
    },
    {
      name: 'Veg Pizza',
      categoryId: 'fast-food',
      foodType: 'VEG',
      price: 239,
      description: 'Crispy thin crust with rich marinara sauce, mozzarella, onions, capsicum, tomatoes, and sweet corn.',
      imageUrl: IMAGES.pizza,
      rating: 4.6,
      reviewCount: 140,
      preparationTime: '20-25 min',
      featured: false,
    },
    {
      name: 'Chicken Burger',
      categoryId: 'fast-food',
      foodType: 'NON_VEG',
      price: 169,
      description: 'Crispy fried chicken patty topped with melted cheddar, fresh iceberg lettuce, and spicy mayo on toasted brioche.',
      imageUrl: IMAGES.burger,
      rating: 4.8,
      reviewCount: 310,
      preparationTime: '15-20 min',
      featured: true,
    },
    {
      name: 'Veg Burger',
      categoryId: 'fast-food',
      foodType: 'VEG',
      price: 139,
      description: 'Crispy spiced potato and vegetable patty layered with tomato, cheese slice, and creamy herb sauce.',
      imageUrl: IMAGES.burger,
      rating: 4.5,
      reviewCount: 170,
      preparationTime: '15-20 min',
      featured: false,
    },
    {
      name: 'French Fries',
      categoryId: 'fast-food',
      foodType: 'VEG',
      price: 119,
      description: 'Golden salted potato fries served crispy hot with tomato ketchup.',
      imageUrl: IMAGES.fries,
      rating: 4.5,
      reviewCount: 260,
      preparationTime: '10-15 min',
      featured: false,
    },
    {
      name: 'Peri Peri Fries',
      categoryId: 'fast-food',
      foodType: 'VEG',
      price: 139,
      description: 'Crispy french fries generously shaken with fiery peri-peri seasoning and herbs.',
      imageUrl: IMAGES.fries,
      rating: 4.8,
      reviewCount: 340,
      preparationTime: '10-15 min',
      featured: true,
    },
    {
      name: 'Cheese Fries',
      categoryId: 'fast-food',
      foodType: 'VEG',
      price: 159,
      description: 'Hot french fries smothered in warm, velvety melted cheese sauce with herbs.',
      imageUrl: IMAGES.fries,
      rating: 4.7,
      reviewCount: 195,
      preparationTime: '10-15 min',
      featured: false,
    },
    {
      name: 'Chicken Sandwich',
      categoryId: 'fast-food',
      foodType: 'NON_VEG',
      price: 149,
      description: 'Triple-layered grilled sandwich packed with seasoned chicken tikka, cucumber, and cheese.',
      imageUrl: IMAGES.sandwich,
      rating: 4.6,
      reviewCount: 130,
      preparationTime: '15-20 min',
      featured: false,
    },

    // DESSERTS
    {
      name: 'Chocolate Ice Cream',
      categoryId: 'desserts',
      foodType: 'VEG',
      price: 119,
      description: 'Double scoop of decadent Belgian dark chocolate ice cream drizzled with fudge.',
      imageUrl: IMAGES.iceCream,
      rating: 4.7,
      reviewCount: 160,
      preparationTime: '5 min',
      featured: false,
    },
    {
      name: 'Vanilla Ice Cream',
      categoryId: 'desserts',
      foodType: 'VEG',
      price: 99,
      description: 'Classic creamy Madagascar vanilla bean ice cream scoop.',
      imageUrl: IMAGES.iceCream,
      rating: 4.5,
      reviewCount: 110,
      preparationTime: '5 min',
      featured: false,
    },
    {
      name: 'Strawberry Ice Cream',
      categoryId: 'desserts',
      foodType: 'VEG',
      price: 109,
      description: 'Refreshing real strawberry puree ice cream with fruit pieces.',
      imageUrl: IMAGES.iceCream,
      rating: 4.6,
      reviewCount: 95,
      preparationTime: '5 min',
      featured: false,
    },
    {
      name: 'Butterscotch Ice Cream',
      categoryId: 'desserts',
      foodType: 'VEG',
      price: 119,
      description: 'Crunchy caramel praline bits folded in smooth butterscotch cream.',
      imageUrl: IMAGES.iceCream,
      rating: 4.7,
      reviewCount: 140,
      preparationTime: '5 min',
      featured: false,
    },
    {
      name: 'Brownie with Ice Cream',
      categoryId: 'desserts',
      foodType: 'VEG',
      price: 169,
      description: 'Warm, gooey walnut brownie served with vanilla ice cream and hot chocolate fudge.',
      imageUrl: IMAGES.brownie,
      rating: 4.9,
      reviewCount: 390,
      preparationTime: '10 min',
      featured: true,
    },
    {
      name: 'Gulab Jamun',
      categoryId: 'desserts',
      foodType: 'VEG',
      price: 89,
      description: 'Two pieces of melt-in-the-mouth fried milk dumplings soaked in cardamom saffron sugar syrup.',
      imageUrl: IMAGES.gulabJamun,
      rating: 4.9,
      reviewCount: 310,
      preparationTime: '5 min',
      featured: true,
    },
    {
      name: 'Rasmalai',
      categoryId: 'desserts',
      foodType: 'VEG',
      price: 119,
      description: 'Two spongy cottage cheese discs soaked in chilled thickened saffron milk with pistachio garnish.',
      imageUrl: IMAGES.rasmalai,
      rating: 4.9,
      reviewCount: 260,
      preparationTime: '5 min',
      featured: true,
    },
    {
      name: 'Chocolate Brownie',
      categoryId: 'desserts',
      foodType: 'VEG',
      price: 129,
      description: 'Rich dark chocolate brownie baked to a fudgy center with chocolate chips.',
      imageUrl: IMAGES.brownie,
      rating: 4.7,
      reviewCount: 130,
      preparationTime: '5 min',
      featured: false,
    },
    {
      name: 'Kulfi',
      categoryId: 'desserts',
      foodType: 'VEG',
      price: 99,
      description: 'Traditional Indian malai kulfi on stick infused with cardamom, almond, and saffron.',
      imageUrl: IMAGES.iceCream,
      rating: 4.8,
      reviewCount: 175,
      preparationTime: '5 min',
      featured: false,
    },

    // BEVERAGES
    {
      name: 'Coke',
      categoryId: 'beverages',
      foodType: 'VEG',
      price: 40,
      description: 'Chilled 330ml can of classic Coca-Cola.',
      imageUrl: IMAGES.beverage,
      rating: 4.5,
      reviewCount: 210,
      preparationTime: '5 min',
      featured: false,
    },
    {
      name: 'Pepsi',
      categoryId: 'beverages',
      foodType: 'VEG',
      price: 40,
      description: 'Chilled 330ml can of crisp Pepsi cola.',
      imageUrl: IMAGES.beverage,
      rating: 4.4,
      reviewCount: 130,
      preparationTime: '5 min',
      featured: false,
    },
    {
      name: 'Sprite',
      categoryId: 'beverages',
      foodType: 'VEG',
      price: 40,
      description: 'Chilled 330ml can of bubbly lemon-lime soda.',
      imageUrl: IMAGES.beverage,
      rating: 4.5,
      reviewCount: 160,
      preparationTime: '5 min',
      featured: false,
    },
    {
      name: 'Fanta',
      categoryId: 'beverages',
      foodType: 'VEG',
      price: 40,
      description: 'Chilled 330ml can of refreshing sparkling orange soda.',
      imageUrl: IMAGES.beverage,
      rating: 4.4,
      reviewCount: 105,
      preparationTime: '5 min',
      featured: false,
    },
    {
      name: 'Fresh Lime Soda',
      categoryId: 'beverages',
      foodType: 'VEG',
      price: 69,
      description: 'Freshly squeezed lime juice with club soda, mint, and choice of sweet or salted.',
      imageUrl: IMAGES.beverage,
      rating: 4.7,
      reviewCount: 190,
      preparationTime: '5-10 min',
      featured: true,
    },
    {
      name: 'Sweet Lassi',
      categoryId: 'beverages',
      foodType: 'VEG',
      price: 79,
      description: 'Traditional Punjabi thick yogurt drink churned with sugar and fragrant cardamom.',
      imageUrl: IMAGES.lassi,
      rating: 4.8,
      reviewCount: 220,
      preparationTime: '5-10 min',
      featured: false,
    },
    {
      name: 'Mango Lassi',
      categoryId: 'beverages',
      foodType: 'VEG',
      price: 99,
      description: 'Creamy yogurt blended with Alphonso mango pulp and topped with chopped nuts.',
      imageUrl: IMAGES.lassi,
      rating: 4.9,
      reviewCount: 340,
      preparationTime: '5-10 min',
      featured: true,
    },
    {
      name: 'Cold Coffee',
      categoryId: 'beverages',
      foodType: 'VEG',
      price: 109,
      description: 'Rich blended espresso with chilled milk, vanilla cream, and cocoa dusting.',
      imageUrl: IMAGES.coldCoffee,
      rating: 4.8,
      reviewCount: 280,
      preparationTime: '5-10 min',
      featured: true,
    },
    {
      name: 'Chocolate Milkshake',
      categoryId: 'beverages',
      foodType: 'VEG',
      price: 129,
      description: 'Thick creamy shake prepared with chocolate ice cream and rich chocolate syrup.',
      imageUrl: IMAGES.milkshake,
      rating: 4.7,
      reviewCount: 195,
      preparationTime: '5-10 min',
      featured: false,
    },
    {
      name: 'Strawberry Milkshake',
      categoryId: 'beverages',
      foodType: 'VEG',
      price: 129,
      description: 'Silky strawberry milkshake crafted with strawberry ice cream and berry drizzle.',
      imageUrl: IMAGES.milkshake,
      rating: 4.6,
      reviewCount: 145,
      preparationTime: '5-10 min',
      featured: false,
    },
    {
      name: 'Mango Milkshake',
      categoryId: 'beverages',
      foodType: 'VEG',
      price: 129,
      description: 'Sweet and luscious shake made with natural Alphonso mango puree and milk.',
      imageUrl: IMAGES.milkshake,
      rating: 4.8,
      reviewCount: 210,
      preparationTime: '5-10 min',
      featured: false,
    },
    {
      name: 'Water Bottle',
      categoryId: 'beverages',
      foodType: 'VEG',
      price: 25,
      description: '1 Litre sealed packaged mineral drinking water bottle.',
      imageUrl: IMAGES.beverage,
      rating: 4.9,
      reviewCount: 500,
      preparationTime: '1 min',
      featured: false,
    },
  ];

  const createdFoods = [];
  for (const item of foodsData) {
    const f = await prisma.food.create({ data: item });
    createdFoods.push(f);
  }
  console.log(`Created ${createdFoods.length} realistic food items.`);

  // 6. Seed Coupons
  await prisma.coupon.createMany({
    data: [
      {
        code: 'DINEDESK10',
        discountType: 'PERCENTAGE',
        discountValue: 10,
        minOrderAmount: 299,
        maxDiscount: 100,
        active: true,
      },
      {
        code: 'WELCOME50',
        discountType: 'FIXED',
        discountValue: 50,
        minOrderAmount: 349,
        active: true,
      },
      {
        code: 'FEAST20',
        discountType: 'PERCENTAGE',
        discountValue: 20,
        minOrderAmount: 799,
        maxDiscount: 250,
        active: true,
      },
      {
        code: 'BIRYANI100',
        discountType: 'FIXED',
        discountValue: 100,
        minOrderAmount: 599,
        active: true,
      },
    ],
  });
  console.log('Coupons created.');

  // 7. Seed Customer Favorites
  const biryani = createdFoods.find((f) => f.name === 'Chicken Dum Biryani') || createdFoods[0];
  const butterChicken = createdFoods.find((f) => f.name === 'Butter Chicken') || createdFoods[1];
  const paneerTikka = createdFoods.find((f) => f.name === 'Paneer Tikka') || createdFoods[2];

  await prisma.favorite.createMany({
    data: [
      { userId: customer.id, foodId: biryani.id },
      { userId: customer.id, foodId: butterChicken.id },
      { userId: customer.id, foodId: paneerTikka.id },
    ],
  });

  // 8. Seed sample orders
  const naan = createdFoods.find((f) => f.name === 'Butter Naan') || createdFoods[3];
  const mangoLassi = createdFoods.find((f) => f.name === 'Mango Lassi') || createdFoods[4];

  // Delivered past order
  const pastOrder = await prisma.order.create({
    data: {
      orderNumber: 'DD-260920-1042',
      userId: customer.id,
      addressId: defaultAddress.id,
      deliveryAddressText: 'Home: Flat 402, Royal Palms, Madhapur, Hyderabad, Telangana - 500081 (Ph: +91 91234 56789)',
      customerName: customer.name,
      customerEmail: customer.email,
      customerPhone: customer.phone || '',
      status: 'DELIVERED',
      paymentMethod: 'ONLINE_MOCK',
      paymentStatus: 'PAID',
      subtotal: 593,
      deliveryFee: 0,
      tax: 30,
      discount: 50,
      total: 573,
      couponCode: 'WELCOME50',
      createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
      items: {
        create: [
          {
            foodId: biryani.id,
            foodName: biryani.name,
            foodImage: biryani.imageUrl,
            foodType: biryani.foodType,
            price: biryani.price,
            quantity: 1,
            subtotal: biryani.price,
          },
          {
            foodId: naan.id,
            foodName: naan.name,
            foodImage: naan.imageUrl,
            foodType: naan.foodType,
            price: naan.price,
            quantity: 2,
            subtotal: naan.price * 2,
          },
          {
            foodId: mangoLassi.id,
            foodName: mangoLassi.name,
            foodImage: mangoLassi.imageUrl,
            foodType: mangoLassi.foodType,
            price: mangoLassi.price,
            quantity: 1,
            subtotal: mangoLassi.price,
          },
        ],
      },
    },
  });

  // Active order currently PREPARING (for live order tracking)
  await prisma.order.create({
    data: {
      orderNumber: 'DD-260924-8831',
      userId: customer.id,
      addressId: defaultAddress.id,
      deliveryAddressText: 'Home: Flat 402, Royal Palms, Madhapur, Hyderabad, Telangana - 500081 (Ph: +91 91234 56789)',
      customerName: customer.name,
      customerEmail: customer.email,
      customerPhone: customer.phone || '',
      status: 'PREPARING',
      paymentMethod: 'COD',
      paymentStatus: 'PENDING',
      subtotal: 508,
      deliveryFee: 0,
      tax: 25,
      discount: 50,
      total: 483,
      couponCode: 'DINEDESK10',
      estimatedDeliveryMinutes: 25,
      createdAt: new Date(Date.now() - 15 * 60 * 1000), // 15 mins ago
      items: {
        create: [
          {
            foodId: butterChicken.id,
            foodName: butterChicken.name,
            foodImage: butterChicken.imageUrl,
            foodType: butterChicken.foodType,
            price: butterChicken.price,
            quantity: 1,
            subtotal: butterChicken.price,
          },
          {
            foodId: paneerTikka.id,
            foodName: paneerTikka.name,
            foodImage: paneerTikka.imageUrl,
            foodType: paneerTikka.foodType,
            price: paneerTikka.price,
            quantity: 1,
            subtotal: paneerTikka.price,
          },
        ],
      },
    },
  });

  // 9. Seed Reviews for delivered items
  await prisma.review.create({
    data: {
      userId: customer.id,
      foodId: biryani.id,
      orderId: pastOrder.id,
      rating: 5,
      comment: 'Authentic aromatic spices and perfectly cooked tender chicken pieces! The best biryani in town.',
      userName: customer.name,
    },
  });

  await prisma.review.create({
    data: {
      userId: customer.id,
      foodId: naan.id,
      orderId: pastOrder.id,
      rating: 5,
      comment: 'Fresh, soft and buttery. Goes incredibly well with the gravies.',
      userName: customer.name,
    },
  });

  console.log('Sample orders and reviews seeded.');
  console.log('Database seeding finished successfully!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
